name: Publish

on:
  push:
    tags:
      - '*'

jobs:

  publish: 
    timeout-minutes: 30
    runs-on: ubuntu-latest
    environment: Publish
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout
      uses: actions/checkout@v3
        
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Setup lodex with custom theme and config
      run: |
        make fetch-latest-lodex
        make custom-config
        make setup-theme

    - name: Setup publish environment
      run: echo 'DOCKER_LOGIN=${{ secrets.DOCKER_LOGIN }}' >> .secrets/.env

    - name: Run publish script
      shell: bash
      run: |
       echo ${{ secrets.DOCKER_LOGIN }}
       chmod +x ${GITHUB_WORKSPACE}/.github/workflows/publish.sh
       ${GITHUB_WORKSPACE}/.github/workflows/publish.sh